site_name: VibeGuide AI Documentation
site_description: Your AI-Powered Cultural Compass for Confident Global Travel
site_author: VibeGuide AI Team
site_url: https://vibeguide-ai.github.io/docs

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - social

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Features:
    - Cultural Intelligence: features/cultural-intelligence.md
    - Real-time Guidance: features/real-time-guidance.md
    - Personalized Insights: features/personalized-insights.md
  - User Guide:
    - Installation: guide/installation.md
    - First Steps: guide/first-steps.md
    - Advanced Features: guide/advanced-features.md
  - API Reference:
    - Authentication: api/authentication.md
    - Endpoints: api/endpoints.md
  - Support:
    - FAQ: support/faq.md
    - Contact: support/contact.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vibeguide-ai
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/vibeguide_ai
    - icon: fontawesome/solid/globe
      link: https://vibeguide.ai

copyright: Copyright &copy; 2024 VibeGuide AI